openapi: 3.0.1
info:
  title: Quasar
  version: v1
paths:
  /topsecret:
    get:
      tags:
        - SateliteReceptor
      responses:
        '200':
          description: Success
    post:
      tags:
        - SateliteReceptor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comunicacion'
          text/json:
            schema:
              $ref: '#/components/schemas/Comunicacion'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Comunicacion'
      responses:
        '201':
          description: Success
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    Comunicacion:
      type: object
      properties:
        satellites:
          type: array
          items:
            $ref: '#/components/schemas/Satellite'
          nullable: true
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
    Satellite:
      type: object
      properties:
        name:
          type: string
          nullable: true
        distance:
          type: number
          format: float
        message:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
